package com.ors.util;

/**
 * @author JAVAPROJECTS
 * 
 */
public class UtilConstants {

	public static final String _ADD_COURSE_JSP = "/jsps/addcourse.jsp";
	public static final String _ADMIN = "admin";
	public static final String _ADMINHOME_JSP = "/jsps/adminhome.jsp";
	public static final String _ASSIGN_COURSE_JSP = "/jsps/assigncourse.jsp";
	public static final String _ASSIGN_REQ_JSP = "/jsps/ViewEmpRequest.jsp";
	public static final String _REQUEST_COURSE_JSP = "/jsps/sendrequest.jsp";
	public static final String _ASSIGNMENT_SHEDULE_FAIL_MESSAGE = "Due To Some Reasons Shedule Assignment Failed(May be this assignment is previously done,-plz check first).";
	public static final String _ASSIGNMENT_SHEDULE_SUCCESS_MESSAGE = "Shedule Assignment Successfully done.";
	public static final String _BEAN = "bean";
	public static final String _CHANGE_PASSWORD_JSP = "/jsps/ChangePassword.jsp";
	public static final String _CHECKUSER = "checkuser";
	public static final String _CONFIG = "config";
	public static final String _COURSE_DELETION_FAIL_MESSAGE = "Course Deletion Failed..";
	public static final String _COURSE_DELETION_SUCCESS_MESSAGE = "Selected Course deleted successfully";
	public static final String _COURSE_DETAILS = "coursedetails";
	public static final String _COURSE_DURATION = "courseduration";
	public static final String _COURSE_ID = "courseid";
	public static final String _COURSE_NAME = "coursename";
	public static final String _COURSE_REG_FAIL_MESSAGE = "Course Registration Failed";
	public static final String _COURSE_REG_SUCCESS_MESSAGE = "Course Registration Done Successfully";
	public static final String _REQUEST_SUCCESS_MESSAGE = "Request Send  Successfully";
	public static final String _REQUEST_FAIL_MESSAGE = "Request Not Sended";
	public static final String _COURSE_SHEDULE_FAIL_MESSAGE = "Course Sheduling Failed(For The Same Date Or Faculty It is Already Sheduled..)";
	public static final String _COURSE_SHEDULE_SUCCESS_MESSAGE = "Course Sheduled Successfully";
	public static final String _CRID = "crid";
	public static final String _DATABASE_DRIVER = "databasedriver";
	public static final String _DATABASE_PASSWORD = "databasepassword";
	public static final String _DATABASE_URL = "databaseurl";
	public static final String _DATABASE_USERNAME = "databaseusername";
	public static final String _DELETE_ASSIGNMENT_JSP = "/jsps/deleteassignment.jsp";
	public static final String _DELETE_COURSE_JSP = "/jsps/deletecourse.jsp";
	public static final String _DELETE_REQUEST_JSP = "/jsps/deleterequest.jsp";
	public static final String _DELETE_SHEDULE_JSP = "/jsps/deleteshedule.jsp";
	public static final String _DEPARTMENT = "department";
	public static final String _DEPARTMENT_HOME_JSP = "/jsps/departmenthome.jsp";
	public static final String _DEPARTMENT_REGISTER_FORM_JSP = "/jsps/DepartmentRegisterform.jsp";
	public static final String _DEPARTMENT_REGISTER_JSP = "/jsps/DepartmentRegisterform.jsp";
	public static final String _FACULTY = "faculty";
	public static final String _EMPLOYEE = "employee";
	public static final String _FACULTY_FLAG = "facultyflag";
	public static final String _FACULTY_ID = "facultyid";
	public static final String _FORMNAME = "formname";
	public static final String _FROMDATE = "fromdate";
	public static final String _INBOX_JSP = "/jsps/inbox.jsp";
	public static final String _INVALID_LOGIN = "Invalid username and password";
	public static final String _LOG_DETAILS_ARRAY = "logdetailsarray";
	public static final String _LOG_DETAILS_USERS = "logdetailsuser";
	public static final String _LOGDETAILS_JSP = "/jsps/logdetails.jsp";
	public static final String _LOGINFORM_JSP = "/jsps/LoginForm.jsp";
	public static final String _LOGOUT_MESSAGE = "logout successfully";
	public static final String _MAIL_DELETION_FAIL_MESSAGE = "Mail Deletion Failed..";
	public static final String _MAIL_DELETION_SUCCESS_MESSAGE = "Selected Mail deleted successfully";
	public static final String _MAIL_SEND_FAIL_MESSAGE = "Mail sending failed...";
	public static final String _MAIL_SEND_SUCCESS_MESSAGE = "Mail sent successfully...";
	public static final String _MESSAGE = "message";;
	public static final String _NEW_REQUEST_MESSAGE_CONTENT = "dear sir,<br/> <br/> Please Check Requests,A New Request Was Sent To You..";
	public static final String _NEW_REQUEST_MESSAGE_SUBJECT = "New Request";
	public static final String _NEW_SHEDULE_ASSIGNMENT_MESSAGE_CONTENT = "dear sir,<br/> <br/> Please Check Ur Assignments,A New Shedule Was Assigned To You..";
	public static final String _NEW_SHEDULE_ASSIGNMENT_MESSAGE_SUBJECT = "New Shedule Assignment";
	public static final String _ON_REQUEST_COORDINATOR = "On-Request Coordinator";
	public static final String _PAGE = "page";
	public static final String _PASSWORD_CHANGE_FAIL_MESSAGE = "Password Change failed.";
	public static final String _PASSWORD_CHANGE_SUCCESS_MESSAGE = "Password Changed Successfully.";
	public static final String _RECEIVER = "receiver";
	public static final String _RECORD_NOT_FOUND = "Record Not Found";
	public static final String _RECOVER_PASSWORD_FAIL_MESSAGE = "Entries not Matched... Try Again";
	public static final String _RECOVER_PASSWORD_JSP = "/jsps/Recoverpassword.jsp";
	public static final String _RECOVER_PASSWORD_SUCCESS_MESSAGE = "Password is ";
	public static final String _REGISTER_DEPARTMENT_FAIL_MESSAGE = "Department Registration Failed";
	public static final String _REGISTER_DEPARTMENT_SUCCESS_MESSAGE = "Department Registered Successfully";
	public static final String _REGISTER_FORM_JSP = "/jsps/Registerform.jsp";
	
	public static final String _EMPREGISTER_FORM_JSP = "/jsps/EmpRegisterform.jsp";
	public static final String _REGISTRATION_FAIL_MESSAGE = "Registration Failed";
	public static final String _REGISTRATION_SUCCESS_MESSAGE = "Registration Success";
	public static final String _REPLY_FAIL_MESSAGE = "Reply Process Failed";
	public static final String _REPLY_REQUEST_JSP = "/jsps/replyrequest.jsp?page=";
	public static final String _REPLY_SUCCESS_MESSAGE = "Replied Succesfully";
	public static final String _REQUEST_DELETION_FAIL_MESSAGE = "Request Deletion Failed..";
	public static final String _REQUEST_DELETION_SUCCESS_MESSAGE = "Selected Requests Deleted successfully";
	public static final String _REQUEST_ID = "requestid";
	public static final String _REQUEST_REPLY_MESSAGE_CONTENT = "dear sir,<br/> <br/> Please Check Request replies,A New Reply Was Sent To You..";
	public static final String _REQUEST_REPLY_MESSAGE_SUBJECT = "Request Reply";
	public static final String _ROLE = "role";
	public static final String _SAME_PASSWORD_ERROR_MESSAGE = "Oldpassword and Newpassword are same..";
	public static final String _SEND_MAIL_JSP = "/jsps/sendmail.jsp";
	public static final String _SEND_REQUEST_FAIL_MESSAGE = "Request Sending Failed";
	public static final String _SEND_REQUEST_SUCCESS_MESSAGE = "Request Sent Successfully";
	public static final String _SET_REQUEST_JSP = "/jsps/setrequest.jsp";
	public static final String _SHEDULE_COURSE_JSP = "/jsps/shedulecourse.jsp";
	public static final String _SHEDULE_DELETION_FAIL_MESSAGE = "Shedule Deletion Failed..";
	public static final String _SHEDULE_DELETION_SUCCESS_MESSAGE = "Selected Course Shedule Deleted successfully";
	public static final String _SHEDULE_ID = "sheduleid";
	public static final String _STATUS = "status";
	public static final String _SUBJECT = "subject";
	public static final String _TO_DATE = "todate";
	public static final String _UPDATE_FAIL_MESSAGE = "Updation Fail";
	public static final String _UPDATE_SUCCESS_MESSAGE = "Updation Success";
	public static final String _USER = "user";
	public static final String _USER_ALREADYEXIST_MESSAGE = "<font color=red>Alreadyexist</font>";
	public static final String _USER_AVAILABLE_MESSAGE = "<font color=green>_/Available</font>";
	public static final String _USER_HOME_JSP = "/jsps/userhome.jsp";
	public static final String _EMP_HOME_JSP = "/jsps/emphome.jsp";
	public static final String _USER_IMAGE_FOLDER = "/userimages";
	public static final String _USER_NOT_FOUND = "usernotfound";
	public static final String _USER_NOT_FOUND_MESSAGE = "There is no user having username ";
	public static final String _USERLOG_JSP = "/jsps/userlog.jsp";
	public static final String _USERNAME = "username";
	public static final String _USERTYPE = "usertype";
	public static final String _VIEW_DEPARTMENT_JSP = "/jsps/viewdept.jsp?username=";
	public static final String _VIEW_PROFILE_JSP = "/jsps/viewprofile.jsp?username=";
	public static final String _VIEW_USER_JSP = "/jsps/viewuser.jsp";
	public static final String _TRUE = "true";
}